#!/bin/bash -e

. ./xi-sys.cfg

# Save old web root page
if [ -f $httpdroot/index.html ]; then
	mv -f $httpdroot/index.html $httpdroot/index.html.orig
fi
if [ -f $httpdroot/index.php ]; then
	mv -f $httpdroot/index.php $httpdroot/index.php.orig
fi

# New web root index page
cp nagiosxi/webroot.php $httpdroot/index.php

if [ "$distro" == "Debian" ] || [ "$distro" == "Ubuntu" ]; then
	cp nagiosxi/webroot.php $httpdroot/../index.php
fi
