#!/bin/bash -e

pkgname="$1"

# Custom CGIs
cp patches/cgi/*.c "$pkgname/cgi"

# Makefile mods for Custom CGIs
patch "$pkgname/cgi/Makefile.in" < patches/cgi-makefile.patch

# Mod for avail.c to add ability to make combined host/service availabilty with filters
patch "$pkgname/cgi/avail.c" < patches/cgi-avail-filtering.patch

# Update the html main.php to remove the following:
# - Checking for updates
# - Most news items and banners
cp -f patches/html/main.php "$pkgname/html/main.php"
