#!/bin/bash -e

pkgname="nsca-2.9.2"

echo "UPGRADE: NSCA is being upgraded..."

# Delete the old archive
rm -rf "$pkgname"

# Extract archive
tar -xzf "$pkgname.tar.gz"

# Make and install 
(
	cd "./$pkgname"
	./configure
	make all
	cp src/nsca /usr/local/nagios/bin
	cp src/send_nsca /usr/local/nagios/libexec
)

echo "UPGRADE: NSCA upgrade OK."
